"""config_registry 的补充注册条目（WebUI 配置页与“拟人 配置”命令共用）。

config_registry 主表此前只覆盖了 config.py 约一半字段，其余字段只能直接改
.env / env.json。本模块以紧凑 spec 形式补齐缺口，由 config_registry 统一构造
ConfigEntry 并复用既有的 secret / kind / advanced 推断逻辑。

spec 约定：
- ``field``：完整字段名（personification_*）；key 自动取去前缀后的部分
- ``t``：bool / int / float / str / list / dict，决定 value_type 与 parser
- 可选键：``group`` / ``choices`` / ``min`` / ``max`` / ``advanced`` / ``hot``
  （hot=False 表示需重启生效）/ ``risk`` / ``example`` / ``aliases`` / ``kind``
"""

from __future__ import annotations

from typing import Any

from .favorability import DEFAULT_FAVORABILITY_EVENT_DELTAS, DEFAULT_FAVORABILITY_LEVELS


def _s(field: str, t: str, default: Any, name: str, desc: str, **extra: Any) -> dict[str, Any]:
    spec: dict[str, Any] = {"field": field, "t": t, "default": default, "name": name, "desc": desc}
    spec.update(extra)
    return spec


EXTRA_CONFIG_SPECS: tuple[dict[str, Any], ...] = (
    # ──────────── 核心开关 ────────────
    _s("personification_whitelist", "list", [], "群白名单",
       "允许进入拟人回复流程的群号列表（JSON 数组）。群开关命令与运行时白名单文件优先于此配置；留空则仅由群开关控制。",
       group="核心开关", example='["123456789","987654321"]', aliases=("白名单", "群白名单")),
    _s("personification_peer_bot_ids", "list", [], "同侪机器人 ID",
       "其他机器人 / Q 群管家的 user_id 列表；命中后本轮静默，避免 bot 与管家互相对话。",
       group="核心开关", example='["2854196310"]', aliases=("机器人名单", "peer_bots")),
    _s("personification_timezone", "str", "Asia/Shanghai", "时区",
       "作息、定时任务使用的 IANA 时区名；修改后建议重启以刷新已注册的定时任务。",
       group="核心开关", hot=False, example="Asia/Shanghai"),
    _s("personification_blacklist_duration", "int", 300, "拉黑时长（秒）",
       "用户被临时拉黑后多少秒内忽略其消息。", group="核心开关", min=0),
    _s("personification_hot_chat_min_pass_rate", "float", 0.40, "热聊保底概率",
       "KY 保护：热聊时 bot 随机发言的最低通过概率；0 完全拦截，0.3 保留 30% 机会。",
       group="核心开关", min=0, max=1),
    _s("personification_max_output_chars", "int", 0, "回复字数上限",
       "单条回复的最大字符数，超出截断；0 = 不限制。", group="核心开关", min=0),
    _s("personification_max_segment_chars", "int", 0, "分段字数上限",
       "回复分段发送时单段最大字符数；0 = 不限制。", group="核心开关", min=0),
    _s("personification_data_dir", "str", "", "数据目录",
       "插件数据根目录；留空使用 localstore 默认路径。修改后需重启。",
       group="核心开关", hot=False, advanced=True),

    # ──────────── 人设与提示词 ────────────
    _s("personification_system_prompt", "str", "", "系统提示词",
       "bot 的人设系统提示词；若配置了 prompt_path / system_path 文件则优先使用文件内容。",
       group="人设提示词", aliases=("人设", "系统提示词", "system_prompt")),
    _s("personification_core_values_enabled", "bool", True, "基础三观底座",
       "是否在所有人设提示词后追加基础三观与判断底线；默认开启，作用于普通回复、YAML、主动消息、日记和空间评论。",
       group="人设提示词", aliases=("三观底座", "判断底线")),
    _s("personification_core_values_prompt", "str", "", "基础三观提示词",
       "追加到系统提示词中的基础价值判断要求；用于维持公共安全、法律责任、尊重生命和不美化伤害等底线。",
       group="人设提示词", aliases=("三观提示词", "价值底线")),
    _s("personification_prompt_path", "str", "", "人设文件路径",
       "外部人设提示词文件路径；非空时覆盖 system_prompt 文本配置。", group="人设提示词"),
    _s("personification_system_path", "str", "", "系统提示词文件路径",
       "外部系统提示词文件路径，与 prompt_path 二选一使用。", group="人设提示词"),
    _s("personification_favorability_enabled", "bool", True, "插件内好感度",
       "启用拟人插件自带好感度体系；关闭后好感度提示、群好感命令、主动加好友等联动不生效。",
       group="人设提示词", aliases=("好感度", "好感系统", "亲密度")),
    _s("personification_favorability_default_score", "float", 0.0, "用户默认好感",
       "新用户首次进入插件内好感度档案时的默认分值（0-100）。",
       group="人设提示词", min=0, max=100, aliases=("默认好感", "用户好感初始值")),
    _s("personification_favorability_group_default_score", "float", 100.0, "群默认好感",
       "新群聊首次进入插件内好感度档案时的默认分值（0-100）。",
       group="人设提示词", min=0, max=100, aliases=("群好感初始值", "群默认亲密度")),
    _s("personification_favorability_levels", "dict", DEFAULT_FAVORABILITY_LEVELS.copy(), "好感度等级阈值",
       "好感度等级到最低分值的映射（JSON 对象）；例如 {\"初见\":0,\"普通\":35,\"挚友\":92}。",
       group="人设提示词", advanced=True,
       aliases=("好感等级", "好感阈值", "亲密度等级"),
       example='{"初见":0,"普通":35,"挚友":92,"亲密":98}'),
    _s("personification_favorability_attitudes", "dict", {}, "好感度态度表",
       "好感度等级到说话态度的映射（JSON 对象）；留空使用内置 10 级默认表。",
       group="人设提示词", advanced=True,
       example='{"初见":"保持基本礼貌","挚友":"无话不谈"}'),
    _s("personification_favorability_event_deltas", "dict", DEFAULT_FAVORABILITY_EVENT_DELTAS.copy(), "好感度事件分值",
       "统一好感度事件到分值变化的映射；内置事件含群氛围好、聊天有趣、永久拉黑、手动调整和每日衰减。",
       group="人设提示词", advanced=True,
       aliases=("好感加分", "好感扣分", "亲密度事件", "事件分值"),
       example='{"group_good_atmosphere":0.1,"user_interesting_chat":0.05,"user_perm_blacklist":-30}'),
    _s("personification_favorability_daily_positive_cap", "float", 5.0, "用户好感每日加分上限",
       "单个用户每天通过正向事件最多累计增加多少好感；模型觉得聊天有趣等事件共享此上限。",
       group="人设提示词", min=0, aliases=("用户加分上限", "好感日上限", "亲密度加分上限")),
    _s("personification_favorability_group_daily_positive_cap", "float", 10.0, "群好感每日加分上限",
       "单个群每天通过氛围良好等正向事件最多累计增加多少群好感。",
       group="人设提示词", min=0, aliases=("群加分上限", "群好感日上限")),
    _s("personification_favorability_daily_negative_cap", "float", 30.0, "好感每日扣分上限",
       "单个用户每天通过负向事件最多累计降低多少好感；永久拉黑等事件受此上限保护。",
       group="人设提示词", min=0, aliases=("扣分上限", "降好感上限", "负向事件上限")),
    _s("personification_favorability_event_log_limit", "int", 50, "好感事件日志条数",
       "每个用户/群好感档案保留最近多少条事件账本；0 表示不保留事件明细。",
       group="人设提示词", min=0, max=500, aliases=("好感日志", "事件账本", "亲密度日志")),
    _s("personification_favorability_decay_enabled", "bool", False, "好感度每日衰减",
       "是否启用每日维护衰减；默认关闭，开启后长期没有好感事件的用户会按配置小幅降低到默认分为止。",
       group="人设提示词", aliases=("好感衰减", "亲密度衰减", "关系冷却")),
    _s("personification_favorability_decay_idle_days", "int", 14, "好感衰减空闲天数",
       "用户连续多少天没有好感事件后才允许每日衰减；只影响用户档案，不自动衰减群默认好感。",
       group="人设提示词", min=1, aliases=("衰减天数", "冷却天数")),
    _s("personification_favorability_decay_delta", "float", -0.20, "好感每日衰减幅度",
       "衰减启用时每日维护应用的分值变化，建议保持为负数且幅度较小；不会降到用户默认好感以下。",
       group="人设提示词", max=0, aliases=("衰减幅度", "每日扣好感")),

    # ──────────── 模型路由（补充） ────────────
    _s("personification_strict_main_model", "bool", False, "严格主模型模式",
       "开启后 intent / review / 闸门 / 表情决策全部走主模型，避免降级到弱模型；默认关闭以优先使用 lite_model 降低回复延迟。",
       group="模型路由", aliases=("严格主模型",)),
    _s("personification_state_model", "str", "", "状态流模型",
       "内在状态 / 日记流使用的模型名；留空复用主模型。", group="模型路由", advanced=True),
    _s("personification_thinking_budget", "int", 0, "思考预算",
       "支持 thinking 的模型的思考 token 预算；0 = 由 provider 默认。", group="模型路由", advanced=True, min=0),
    _s("personification_include_thoughts", "bool", True, "返回思考过程",
       "请求 thinking 模型时是否要求返回思考摘要（仅影响日志观测，不影响回复内容）。",
       group="模型路由", advanced=True),

    # ──────────── 遗留单模型配置（已被 API Provider 池取代） ────────────
    _s("personification_api_type", "str", "openai", "[遗留] 主模型 API 类型",
       "遗留单模型配置；仅在 API Provider 池（api_pools）为空时作为回退。推荐改用 API Provider 池。",
       group="遗留配置", advanced=True),
    _s("personification_api_url", "str", "", "[遗留] 主模型 API 地址",
       "遗留单模型配置；仅在 API Provider 池为空时作为回退。", group="遗留配置", advanced=True),
    _s("personification_api_key", "str", "", "[遗留] 主模型 API 密钥",
       "遗留单模型配置；仅在 API Provider 池为空时作为回退。", group="遗留配置", advanced=True),
    _s("personification_model", "str", "gpt-4o-mini", "[遗留] 主模型名称",
       "遗留单模型配置；仅在 API Provider 池为空时作为回退。", group="遗留配置", advanced=True),
    _s("personification_compress_api_type", "str", "", "[废弃] 压缩模型 API 类型",
       "已废弃：仅在未配置 fallback_* 时作为兜底别名读取，请改用模型回退配置。", group="遗留配置", advanced=True),
    _s("personification_compress_api_url", "str", "", "[废弃] 压缩模型 API 地址",
       "已废弃：仅在未配置 fallback_* 时作为兜底别名读取。", group="遗留配置", advanced=True),
    _s("personification_compress_api_key", "str", "", "[废弃] 压缩模型 API 密钥",
       "已废弃：仅在未配置 fallback_* 时作为兜底别名读取。", group="遗留配置", advanced=True),
    _s("personification_compress_model", "str", "", "[废弃] 压缩模型名称",
       "已废弃：仅在未配置 fallback_* 时作为兜底别名读取。", group="遗留配置", advanced=True),
    _s("personification_web_search", "bool", True, "[废弃] 联网搜索",
       "已废弃：请改用 tool_web_search_enabled / web_search skill 配置。", group="遗留配置", advanced=True),

    # ──────────── CLI OAuth 凭证 ────────────
    _s("personification_codex_auth_path", "str", "", "Codex 凭证路径",
       "OpenAI Codex OAuth 凭证文件路径；留空自动查找 ~/.codex/auth.json。", group="CLI 凭证", advanced=True),
    _s("personification_gemini_cli_auth_path", "str", "", "Gemini CLI 凭证路径",
       "gemini-cli OAuth 凭证路径；留空按 ~/.gemini/oauth_creds.json、$GEMINI_HOME 顺序查找。",
       group="CLI 凭证", advanced=True),
    _s("personification_gemini_cli_project", "str", "", "Gemini CLI 项目",
       "cloudaicompanionProject；留空时自动解析并缓存。", group="CLI 凭证", advanced=True),
    _s("personification_antigravity_cli_auth_path", "str", "", "Antigravity 凭证路径",
       "Antigravity CLI OAuth 凭证路径；留空自动查找，找不到时回退 gemini-cli 凭证。",
       group="CLI 凭证", advanced=True),
    _s("personification_antigravity_cli_project", "str", "", "Antigravity 项目",
       "Antigravity companion project；留空时自动解析，再兼容 gemini-cli/gcloud 配置。",
       group="CLI 凭证", advanced=True),
    _s("personification_claude_code_auth_path", "str", "", "Claude Code 凭证路径",
       "claude-code OAuth 凭证路径；留空按 ~/.claude/.credentials.json、$CLAUDE_CONFIG_DIR 顺序查找。",
       group="CLI 凭证", advanced=True),

    # ──────────── 画像（补充） ────────────
    _s("personification_persona_api_type", "str", "", "画像模型 API 类型",
       "用户画像分析模型的 API 类型；留空复用主模型。", group="画像", advanced=True),
    _s("personification_persona_api_url", "str", "", "画像模型 API 地址",
       "用户画像分析模型的 API 地址；留空复用主模型。", group="画像", advanced=True),
    _s("personification_persona_api_key", "str", "", "画像模型 API 密钥",
       "用户画像分析模型的 API 密钥；留空复用主模型。", group="画像", advanced=True),
    _s("personification_persona_model", "str", "", "画像模型名称",
       "用户画像分析使用的模型名；留空复用主模型。", group="画像", advanced=True),
    _s("personification_persona_data_path", "str", "", "画像数据路径",
       "用户画像数据存储路径；留空使用默认数据目录。", group="画像", advanced=True, hot=False),
    _s("personification_persona_snippet_max_chars", "int", 150, "画像片段字数上限",
       "注入上下文的单条画像片段最大字符数。", group="画像", min=0),
    _s("personification_persona_prompt_max_chars", "int", 120, "画像提示字数上限",
       "注入系统提示词的画像摘要最大字符数。", group="画像", min=0),
    _s("personification_persona_responder_json_enabled", "bool", False, "画像 JSON 应答",
       "画像响应器是否使用 JSON 结构化输出（实验特性）。", group="画像", advanced=True),

    # ──────────── 视觉理解 ────────────
    _s("personification_image_input_mode", "str", "auto", "图片输入模式",
       "auto=支持视觉时直传否则转摘要；direct=强制直传；summary=强制视觉摘要；disabled=忽略图片。",
       group="视觉理解", choices=("auto", "direct", "summary", "disabled")),
    _s("personification_image_detail", "str", "auto", "图片细节等级",
       "传给视觉模型的图片 detail 参数；low 更省 token，high 识别更准。",
       group="视觉理解", choices=("auto", "low", "high")),
    _s("personification_sticker_vision_max", "int", 3, "单轮表情视觉数",
       "单轮最多送入视觉模型分析的表情包/图片数量。", group="视觉理解", min=0, advanced=True),
    _s("personification_gif_understanding_enabled", "bool", False, "GIF 理解",
       "是否理解 GIF / 动态表情。默认关闭；开启后会抽取关键帧生成一张拼图，再交给当前视觉模型生成上下文摘要。",
       group="视觉理解"),
    _s("personification_gif_understanding_timeout", "float", 12.0, "GIF 理解超时（秒）",
       "单条 GIF 下载、抽帧与视觉摘要的总超时预算；运行时硬限制最高 35 秒，保证额外等待低于 40 秒。",
       group="视觉理解", min=1, max=35, advanced=True),
    _s("personification_gif_max_bytes", "int", 8388608, "GIF 最大体积",
       "超过该字节数的 GIF 不做理解，只注入动态表情占位符。", group="视觉理解", min=65536, advanced=True),
    _s("personification_gif_max_decode_frames", "int", 180, "GIF 解码帧上限",
       "单个 GIF 最多解码多少帧用于抽样，避免超长动图拖慢回复。", group="视觉理解", min=1, max=360, advanced=True),
    _s("personification_gif_sample_frames", "int", 8, "GIF 抽帧数量",
       "生成关键帧拼图时最多保留多少帧；运行时会根据总帧数按 2-6 帧间隔抽样。", group="视觉理解", min=1, max=12, advanced=True),
    _s("personification_gif_contact_sheet_long_edge", "int", 1600, "GIF 拼图长边",
       "抽帧拼图的目标长边像素，越大越清晰但视觉 token 和处理成本越高。", group="视觉理解", min=512, max=2400, advanced=True),
    _s("personification_gif_max_per_turn", "int", 1, "单轮 GIF 理解数",
       "同一轮消息最多理解多少个 GIF；超过后只注入动态表情占位符，避免多 GIF 拖慢回复。", group="视觉理解", min=1, max=3, advanced=True),
    _s("personification_gif_summary_cache_enabled", "bool", True, "GIF 摘要缓存",
       "按 GIF 内容哈希缓存视觉摘要，重复动态表情可直接复用摘要以降低延迟。", group="视觉理解", advanced=True),
    _s("personification_vision_fallback_enabled", "bool", True, "视觉回退",
       "主模型不支持视觉时是否自动切换到视觉回退 provider。", group="视觉理解"),
    _s("personification_vision_fallback_provider", "str", "", "视觉回退 Provider",
       "视觉回退使用的 provider 名称（对应 API 池中的 name）；留空自动选择。", group="视觉理解", advanced=True),
    _s("personification_vision_fallback_model", "str", "", "视觉回退模型",
       "视觉回退使用的模型名；留空用 provider 默认。", group="视觉理解", advanced=True),
    _s("personification_image_search_api_key", "str", "", "图片搜索 API Key",
       "图片搜索工具的 API 密钥；留空禁用相应工具。", group="视觉理解"),

    # ──────────── 表情包（补充） ────────────
    _s("personification_sticker_collect_meme_policy", "str", "reject", "梗图收集策略",
       "收集表情包时对 meme 风格图片的处理：reject=拒收，accept=接收，review=待审。",
       group="表情包", choices=("reject", "accept", "review")),
    _s("personification_sticker_library_soft_limit", "int", 800, "表情库软上限",
       "表情库容量软上限，超出后开始低优先级淘汰。", group="表情包", min=0, advanced=True),
    _s("personification_sticker_library_hard_limit", "int", 1200, "表情库硬上限",
       "表情库容量硬上限，达到后停止收集。", group="表情包", min=0, advanced=True),
    _s("personification_sticker_per_mood_limit", "int", 50, "单情绪表情上限",
       "每个情绪标签下最多保留的表情数量。", group="表情包", min=0, advanced=True),
    _s("personification_sticker_collect_cooldown_seconds", "int", 60, "表情收集冷却（秒）",
       "两次表情收集之间的最小间隔。", group="表情包", min=0, advanced=True),
    _s("personification_sticker_collect_sample_rate", "float", 0.5, "表情收集采样率",
       "群消息中表情包进入收集流程的采样概率（0-1）。", group="表情包", min=0, max=1),
    _s("personification_sticker_collect_min_confidence", "float", 0.7, "表情收集置信度",
       "视觉打标置信度低于该值的表情不入库（0-1）。", group="表情包", min=0, max=1, advanced=True),
    _s("personification_sticker_second_judge_enabled", "bool", False, "表情二次判定",
       "发送前是否用 LLM 再次判断表情与语境是否匹配。", group="表情包", advanced=True),
    _s("personification_sticker_curator_enabled", "bool", False, "表情库自动整理",
       "定期用 LLM 整理表情库（去重、淘汰低质量表情）。", group="表情包"),
    _s("personification_sticker_curator_interval_days", "int", 3, "整理间隔（天）",
       "表情库自动整理的运行间隔。", group="表情包", min=1, advanced=True),
    _s("personification_qq_expression_enabled", "bool", True, "QQ 表情启用",
       "允许回复发送层把 [QQ表情:笑哭] 等标记转成 QQ 小黄脸、超级表情或收藏/推荐表情。",
       group="表情包", aliases=("QQ表情", "小黄脸")),
    _s("personification_qq_expression_probability", "float", 0.08, "QQ 小黄脸概率",
       "普通回复中低概率自动附加 QQ 小黄脸；用户明确要求发表情时不受概率限制。",
       group="表情包", min=0, max=1),
    _s("personification_qq_expression_cooldown_seconds", "int", 180, "QQ 表情冷却（秒）",
       "同一群/私聊自动附加 QQ 表情之间的最小间隔；显式发表情请求不受限制。",
       group="表情包", min=0, advanced=True),
    _s("personification_qq_expression_daily_limit", "int", 30, "QQ 表情日上限",
       "每个群/私聊每天自动附加 QQ 表情的上限；0 = 不限制。",
       group="表情包", min=0, advanced=True),
    _s("personification_qq_expression_super_probability", "float", 0.02, "QQ 超级表情概率",
       "水群/接梗场景自动附加 QQ 表情时，升级为超级表情的概率。",
       group="表情包", min=0, max=1, advanced=True),
    _s("personification_qq_expression_triple_probability", "float", 0.02, "QQ 三连表情概率",
       "水群/接梗场景自动附加 QQ 表情时，发送三个连续普通小黄脸的概率。",
       group="表情包", min=0, max=1, advanced=True),
    _s("personification_qq_favorite_expression_probability", "float", 0.02, "QQ 收藏/推荐表情概率",
       "自动附加 QQ 表情时改用协议端推荐/收藏图片表情的概率；协议端不支持时会跳过。",
       group="表情包", min=0, max=1, advanced=True),
    _s("personification_labeler_api_type", "str", "openai", "打标模型 API 类型",
       "表情包视觉打标模型的 API 类型。", group="表情包", advanced=True),
    _s("personification_labeler_api_url", "str", "", "打标模型 API 地址",
       "表情包视觉打标模型的 API 地址；留空复用主模型。", group="表情包", advanced=True),
    _s("personification_labeler_api_key", "str", "", "打标模型 API 密钥",
       "表情包视觉打标模型的 API 密钥；留空复用主模型。", group="表情包", advanced=True),
    _s("personification_labeler_model", "str", "", "打标模型名称",
       "表情包视觉打标使用的模型名；留空复用主模型，填写后仅覆盖表情包/视觉打标角色。", group="表情包", advanced=True),
    _s("personification_labeler_concurrency", "int", 3, "打标并发数",
       "批量打标时的并发请求数。", group="表情包", min=1, advanced=True),

    # ──────────── TTS 语音（补充） ────────────
    _s("personification_tts_enabled", "bool", False, "TTS 启用",
       "TTS 语音能力总开关；关闭后语音命令与自动语音都不可用。", group="TTS 语音",
       aliases=("语音开关", "tts开关")),
    _s("personification_tts_api_url", "str", "https://api.xiaomimimo.com/v1", "TTS API 地址",
       "TTS 服务的 API 地址。", group="TTS 语音"),
    _s("personification_tts_api_key", "str", "", "TTS API 密钥",
       "TTS 服务的 API 密钥。", group="TTS 语音"),
    _s("personification_tts_auto_enabled", "bool", False, "自动语音回复",
       "是否按概率把文本回复自动转成语音发送。", group="TTS 语音"),
    _s("personification_tts_auto_probability", "float", 0.2, "自动语音概率",
       "自动语音回复的触发概率（0-1）。", group="TTS 语音", min=0, max=1),
    _s("personification_tts_voice_clone", "str", "", "克隆音色 ID",
       "voice clone 模式使用的音色 ID；与 tts_voice_clone_path 二选一。", group="TTS 语音", advanced=True),
    _s("personification_tts_default_format", "str", "wav", "语音格式",
       "TTS 输出音频格式（如 wav / mp3），需服务端支持。", group="TTS 语音", advanced=True),
    _s("personification_tts_max_chars_per_segment", "int", 120, "语音分段字数",
       "长文本转语音时单段最大字符数。", group="TTS 语音", min=1, advanced=True),
    _s("personification_tts_timeout", "int", 60, "TTS 超时（秒）",
       "单次 TTS 合成请求的超时时间。", group="TTS 语音", min=1, advanced=True),
    _s("personification_tts_style_planner_enabled", "bool", False, "语音风格规划",
       "合成前用 LLM 规划语气/情绪风格（额外一次 LLM 调用）。", group="TTS 语音", advanced=True),
    _s("personification_tts_command_prefixes", "list", ["说", "朗读", "配音"], "语音命令前缀",
       "触发语音回复的命令前缀列表（JSON 数组）。", group="TTS 语音",
       example='["说","朗读","配音"]'),
    _s("personification_tts_private_force_auto", "bool", False, "私聊强制语音",
       "私聊场景是否无视概率强制自动语音回复。", group="TTS 语音", advanced=True),
    _s("personification_tts_group_default_enabled", "bool", True, "群语音默认开",
       "新群的语音回复默认开关（群内可单独覆盖）。", group="TTS 语音"),

    # ──────────── QQ 空间（补充） ────────────
    _s("personification_qzone_enabled", "bool", False, "QQ 空间启用",
       "QQ 空间功能总开关（发说说、点赞、评论、回复）。", group="QQ 空间"),
    _s("personification_qzone_cookie", "str", "", "QQ 空间 Cookie",
       "访问 QQ 空间所需的 Cookie；过期后空间功能静默失效，需重新抓取。",
       group="QQ 空间", risk="Cookie 等同账号凭证，请勿外泄。"),
    _s("personification_qzone_check_interval", "int", 30, "空间检查间隔（分钟）",
       "主动发说说决策的检查周期。", group="QQ 空间", min=1, advanced=True),
    _s("personification_qzone_monthly_limit", "int", 30, "每月说说上限",
       "每月最多主动发布的说说条数。", group="QQ 空间", min=0),
    _s("personification_qzone_agent_max_steps", "int", 4, "发说说工具步数上限",
       "发说说时调用 web_search 等工具修正内容的最大循环步数。", group="QQ 空间", min=1, advanced=True),
    _s("personification_qzone_probability", "float", 0.35, "发说说概率",
       "每次检查时触发发说说的概率（0-1）。", group="QQ 空间", min=0, max=1),
    _s("personification_qzone_min_interval_hours", "float", 6.0, "说说最小间隔（小时）",
       "两条说说之间的最小间隔时间。", group="QQ 空间", min=0),
    _s("personification_qzone_outbound_reply_lookback_hours", "float", 72.0, "说说回评回看（小时）",
       "回复自己说说下新评论时回看的时间窗口。", group="QQ 空间", min=1, advanced=True),

    # ──────────── 主动私聊（补充） ────────────
    _s("personification_proactive_probability", "float", 0.18, "主动私聊概率",
       "满足条件后实际发起主动私聊的概率（0-1）。", group="主动私聊", min=0, max=1),
    _s("personification_proactive_unsuitable_prob", "float", 0.18, "不适宜时段概率",
       "判定为不适宜时段时仍尝试主动私聊的概率（0-1）。", group="主动私聊", min=0, max=1, advanced=True),
    _s("personification_proactive_without_signin", "bool", True, "无签到也主动",
       "用户当天没有互动（签到）时是否也允许主动私聊。", group="主动私聊", advanced=True),

    # ──────────── 群行为 ────────────
    _s("personification_group_idle_enabled", "bool", False, "群闲时主动发话",
       "群长时间无消息后 bot 主动找话题。", group="群行为", aliases=("主动水群",)),
    _s("personification_group_idle_minutes", "int", 90, "闲时阈值（分钟）",
       "群多少分钟无消息后触发主动发话。", group="群行为", min=1),
    _s("personification_group_idle_check_interval", "int", 15, "闲时检查间隔（分钟）",
       "主动发话的定时检测频率。", group="群行为", min=1, advanced=True),
    _s("personification_group_idle_daily_limit", "int", 1, "闲时发话日上限",
       "每个群每天最多主动发话次数。", group="群行为", min=0),
    _s("personification_group_chat_active_minutes", "int", 12, "接话活跃窗口（分钟）",
       "bot 刚接过话后保留的活跃窗口时长，窗口内更容易继续顺着话题聊。", group="群行为", advanced=True, min=0),
    _s("personification_group_chat_follow_probability", "float", 0.96, "活跃窗口跟聊概率",
       "活跃窗口内继续接话的概率（0-1）。", group="群行为", min=0, max=1, advanced=True),
    _s("personification_group_quiet_hour_start", "int", 0, "群深夜禁发开始",
       "深夜禁止群内发言的起始小时（含）。", group="群行为", min=0, max=23),
    _s("personification_group_quiet_hour_end", "int", 8, "群深夜禁发结束",
       "深夜禁止群内发言的结束小时（不含）。", group="群行为", min=0, max=24),
    _s("personification_group_summary_enabled", "bool", True, "群话题摘要",
       "是否定期生成群话题摘要并注入上下文。", group="群行为"),
    _s("personification_group_style_auto_analyze_threshold", "int", 200, "群风格分析阈值",
       "群消息累计达到该条数后首次触发自动风格分析。", group="群行为", advanced=True, min=1),
    _s("personification_group_style_auto_analyze_min_new_messages", "int", 50, "风格再分析新增消息",
       "距上次自动分析至少新增多少条消息才允许再次触发。", group="群行为", advanced=True, min=1),
    _s("personification_group_style_auto_analyze_cooldown_hours", "float", 12.0, "风格分析冷却（小时）",
       "两次自动风格分析的最小间隔。", group="群行为", advanced=True, min=0),
    _s("personification_style_api_type", "str", "", "风格分析模型 API 类型",
       "群风格分析模型的 API 类型；留空复用主模型。", group="群行为", advanced=True),
    _s("personification_style_api_url", "str", "", "风格分析模型 API 地址",
       "群风格分析模型的 API 地址；留空复用主模型。", group="群行为", advanced=True),
    _s("personification_style_api_key", "str", "", "风格分析模型 API 密钥",
       "群风格分析模型的 API 密钥；留空复用主模型。", group="群行为", advanced=True),
    _s("personification_style_api_model", "str", "", "风格分析模型名称",
       "群风格分析使用的模型名；留空复用主模型。", group="群行为", advanced=True),

    # ──────────── 后台任务（补充） ────────────
    _s("personification_social_morning_greeting_enabled", "bool", True, "早安问候",
       "Social Intelligence：早安问候场景开关（需总开关开启）。", group="后台任务"),
    _s("personification_social_evening_greeting_enabled", "bool", True, "晚安问候",
       "Social Intelligence：晚安问候场景开关（需总开关开启）。", group="后台任务"),
    _s("personification_social_greeting_cooldown_seconds", "int", 64800, "问候冷却（秒）",
       "同一用户两次问候的最小间隔，默认 18 小时。", group="后台任务", min=0, advanced=True),
    _s("personification_social_greeting_max_recipients", "int", 8, "问候人数上限",
       "每次早晚问候最多发给多少人（按最近活跃排序）。", group="后台任务", min=0),
    _s("personification_social_news_users", "list", [], "新闻推送用户",
       "定时新闻推送的私聊对象 QQ 列表（JSON 数组）。", group="后台任务", example='["10001"]'),
    _s("personification_social_news_groups", "list", [], "新闻推送群",
       "定时新闻推送的群号列表（JSON 数组）。", group="后台任务", example='["123456789"]'),
    _s("personification_social_news_cooldown_seconds", "int", 72000, "新闻推送冷却（秒）",
       "同一对象两次新闻推送的最小间隔，默认 20 小时。", group="后台任务", min=0, advanced=True),
    _s("personification_social_topic_followup_window_hours", "int", 24, "话题跟进窗口（小时）",
       "话题延续仅在承诺时间 ± 窗口小时内跟进。", group="后台任务", min=1, advanced=True),
    _s("personification_social_topic_followup_cooldown_seconds", "int", 43200, "话题跟进冷却（秒）",
       "同一用户两次话题跟进的最小间隔，默认 12 小时。", group="后台任务", min=0, advanced=True),
    _s("personification_social_festival_max_recipients", "int", 20, "节日祝福人数上限",
       "每个节日最多发送祝福的人数。", group="后台任务", min=0),
    _s("personification_social_festival_cooldown_seconds", "int", 82800, "节日祝福冷却（秒）",
       "同一用户两次节日祝福的最小间隔，默认 23 小时。", group="后台任务", min=0, advanced=True),
    _s("personification_active_learning_enabled", "bool", False, "主动学习",
       "后台主动学习（从对话中提炼知识）开关。", group="后台任务"),
    _s("personification_active_learning_daily_quota", "int", 5, "主动学习日配额",
       "每天主动学习任务的最大次数。", group="后台任务", min=0, advanced=True),
    _s("personification_relation_evolution_enabled", "bool", False, "关系演化",
       "后台关系演化（基于互动调整好感关系）开关。", group="后台任务"),
    _s("personification_relation_evolution_daily_quota", "int", 10, "关系演化日配额",
       "每天关系演化任务的最大次数。", group="后台任务", min=0, advanced=True),
    _s("personification_friend_request_enabled", "bool", False, "主动加好友",
       "好感度足够的群成员，bot 是否主动发起好友请求。", group="后台任务",
       risk="主动加好友属于外显行为，建议确认人设与场景后再开启。"),
    _s("personification_friend_request_min_fav", "float", 85.0, "加好友好感阈值",
       "好感度达到该值才会考虑主动加好友。", group="后台任务", min=0),
    _s("personification_friend_request_daily_limit", "int", 2, "加好友日上限",
       "每天最多主动发起的好友请求数。", group="后台任务", min=0),

    # ──────────── 知识库（补充） ────────────
    _s("personification_group_knowledge_enabled", "bool", False, "群知识库",
       "群知识库功能总开关（构建由 autobuild 配置控制）。", group="知识库"),
    _s("personification_lorebook_enabled", "bool", False, "Lorebook",
       "Lorebook 世界书注入功能开关。", group="知识库"),
    _s("personification_cross_verify_enabled", "bool", False, "交叉验证",
       "回答事实类问题时用多来源交叉验证（额外搜索与 LLM 调用）。", group="联网搜索", advanced=True),

    # ──────────── 联网搜索 / 工具（补充） ────────────
    _s("personification_web_search_always", "bool", False, "强制联网搜索",
       "每轮回复都强制执行联网搜索（显著增加延迟与 token，仅调试用）。", group="联网搜索", advanced=True),
    _s("personification_parallel_research_pages_per_worker", "int", 20, "并行研究页数",
       "并行研究每个 worker 最多抓取的页面数。", group="联网搜索", min=1, advanced=True),
    _s("personification_weather_api", "str", "wttr", "天气数据源",
       "天气查询工具使用的数据源。", group="工具"),
    _s("personification_github_token", "str", "", "GitHub Token",
       "GitHub 相关工具使用的访问令牌；留空时受未认证速率限制。", group="工具"),
    _s("personification_fandom_wikis", "dict", {}, "Fandom Wiki 映射",
       "Fandom 百科工具的 wiki 名称到子域映射（JSON 对象）；留空用内置默认。",
       group="百科工具", advanced=True, example='{"原神":"genshin-impact"}'),
    _s("personification_game_info_enabled", "bool", True, "游戏信息工具",
       "聚合游戏更新公告/攻略/剧情的 game_info 工具开关。", group="工具"),
    _s("personification_game_info_timeout", "float", 15.0, "游戏信息超时（秒）",
       "game_info 工具单次抓取的超时时间。", group="工具", min=1, advanced=True),
    _s("personification_game_info_community_sites", "list", [], "攻略社区站点",
       "攻略/技巧定向搜索附加的社区站点白名单（JSON 数组）；留空用内置默认。",
       group="工具", advanced=True),
    _s("personification_60s_enabled", "bool", True, "60s 新闻 API",
       "每日新闻等 60s API 数据源开关。", group="工具"),
    _s("personification_60s_api_base", "str", "https://60s.viki.moe", "60s API 地址",
       "60s API 的公共服务地址。", group="工具", advanced=True),
    _s("personification_60s_local_api_base", "str", "http://127.0.0.1:4399", "60s 本地 API",
       "本地部署的 60s API 地址（优先于公共地址探测）。", group="工具", advanced=True),

    # ──────────── Skill 扩展 ────────────
    _s("personification_use_skillpacks", "bool", False, "启用 Skillpacks",
       "用标准 skillpack 体系加载工具（news/weather/web_search 等）。", group="Skill 扩展", hot=False),
    _s("personification_skills_path", "str", "", "自定义 Skill 目录",
       "用户自定义 skillpack 目录；修改后需重启加载。", group="Skill 扩展", hot=False),
    _s("personification_skill_sources", "list", [], "远程 Skill 源",
       "远程公开 skill 源列表（本地目录 / zip / GitHub 仓库 URL）；修改后需重启加载。",
       group="Skill 扩展", hot=False,
       example='[{"name":"pack","source":"https://github.com/example/skill-weather","ref":"main"}]'),
    _s("personification_skill_remote_enabled", "bool", False, "远程 Skill 启用",
       "是否允许加载远程公开 skill 源。", group="Skill 扩展", hot=False),
    _s("personification_skill_cache_dir", "str", "", "Skill 缓存目录",
       "远程 skill 的本地缓存目录；留空用 data/personification/skill_cache。",
       group="Skill 扩展", hot=False, advanced=True),
    _s("personification_skill_update_interval", "int", 3600, "Skill 更新间隔（秒）",
       "远程 skill 源的更新检查周期。", group="Skill 扩展", min=60, advanced=True),
    _s("personification_skill_default_timeout", "int", 15, "Skill 执行超时（秒）",
       "skill 子进程执行的默认超时。", group="Skill 扩展", min=1, advanced=True),
    _s("personification_skill_mcp_timeout", "int", 20, "Skill MCP 超时（秒）",
       "MCP 兼容 skill 的初始化与调用超时。", group="Skill 扩展", min=1, advanced=True),
    _s("personification_skill_allow_unsafe_external", "bool", False, "允许非隔离外部 Skill",
       "允许不可信外部 skill 直接在宿主进程内执行 build_tools/register。",
       group="Skill 扩展", advanced=True,
       risk="高风险：外部代码将获得宿主进程权限，仅在完全信任来源时开启。"),
    _s("personification_skill_require_admin_review", "bool", True, "外部 Skill 需审核",
       "远程 skill 加载前需管理员审核确认。", group="Skill 扩展"),
    _s("personification_plugin_invoker_enabled", "bool", False, "插件调用器",
       "允许 bot 代为执行其它已安装插件的命令并转述结果。", group="Skill 扩展",
       risk="bot 将能触发其它插件的命令，请配合 allowlist/blocklist 使用。"),
    _s("personification_plugin_invoker_allowlist", "list", [], "插件调用白名单",
       "非空时仅允许调用这些插件（JSON 数组）。", group="Skill 扩展", advanced=True),
    _s("personification_plugin_invoker_blocklist", "list", [], "插件调用黑名单",
       "禁止调用的插件名或 插件名:命令（JSON 数组）。", group="Skill 扩展", advanced=True),
    _s("personification_plugin_invoker_max_calls_per_turn", "int", 2, "插件调用轮上限",
       "单轮回复内最多代为执行的插件命令数。", group="Skill 扩展", min=1, advanced=True),
    _s("personification_plugin_invoker_capture_timeout", "float", 15.0, "插件捕获超时（秒）",
       "等待插件输出的超时时间。", group="Skill 扩展", min=1, advanced=True),
    _s("personification_plugin_invoker_max_output_chars", "int", 1500, "插件输出字数上限",
       "转述插件输出时的最大字符数。", group="Skill 扩展", min=100, advanced=True),
    _s("personification_plugin_invoker_extra_danger_keywords", "list", [], "插件危险关键词",
       "附加的危险命令关键词（命中即拒绝执行，JSON 数组）。", group="Skill 扩展", advanced=True),

    # ──────────── 拟人行为 ────────────
    _s("personification_protocol_extensions", "str", "auto", "协议扩展档位",
       "扩展 API（贴表情/拍一拍/输入状态）的协议端档位；auto=自动识别，none=全部禁用。",
       group="拟人行为", choices=("auto", "none", "napcat", "lagrange", "llonebot", "gocq")),
    _s("personification_humanize_typing_enabled", "bool", True, "打字延迟",
       "首条回复按 阅读时间+字数/打字速度-模型已耗时 延迟发送，消除秒回长文的 bot 感。",
       group="拟人行为", aliases=("打字延迟", "typing_delay")),
    _s("personification_humanize_typing_cps", "float", 7.0, "打字速度（字/秒）",
       "模拟打字速度，越小延迟越长。", group="拟人行为", min=1, max=50, advanced=True),
    _s("personification_humanize_typing_max_delay", "float", 5.0, "打字延迟上限（秒）",
       "单条消息模拟延迟的最大值。", group="拟人行为", min=0, max=30, advanced=True),
    _s("personification_humanize_fragment_style", "str", "prompt", "碎片化输出",
       "prompt=提示词引导模型像群友一样拆成 1-3 条短消息；off=不干预。",
       group="拟人行为", choices=("off", "prompt")),
    _s("personification_humanize_quote_reply_enabled", "bool", True, "引用回复",
       "跨楼回复（被回复消息之后已有较多新消息）时自动带引用。", group="拟人行为"),
    _s("personification_humanize_quote_reply_min_gap", "int", 4, "引用触发间隔",
       "合并批内被回复消息之后至少有多少条新消息才触发引用。", group="拟人行为", min=1, advanced=True),
    _s("personification_humanize_reaction_enabled", "bool", True, "贴表情回应",
       "判定不回复（NO_REPLY）时按概率给消息贴表情，代替完全沉默；协议端不支持时自动跳过。",
       group="拟人行为", aliases=("贴表情", "表情回应")),
    _s("personification_humanize_reaction_probability", "float", 0.25, "贴表情概率",
       "NO_REPLY 时触发贴表情的概率（0-1）。", group="拟人行为", min=0, max=1),
    _s("personification_humanize_reaction_daily_limit", "int", 20, "贴表情日上限",
       "每个群每天最多贴表情次数。", group="拟人行为", min=0, advanced=True),
    _s("personification_humanize_typo_probability", "float", 0.0, "错别字概率",
       "闲聊短句低概率注入同音错字并跟发 *修正；0=关闭，建议 0.03。",
       group="拟人行为", min=0, max=0.2, advanced=True),
    _s("personification_humanize_poke_back_probability", "float", 0.3, "拍回去概率",
       "被拍一拍后拍回去的概率（0-1）。", group="拟人行为", min=0, max=1),
    _s("personification_humanize_proactive_poke_enabled", "bool", False, "主动拍一拍",
       "高好感用户冒泡且本轮不回文本时小概率主动拍一拍（每群每日上限 3 次）。",
       group="拟人行为"),
    _s("personification_humanize_at_enabled", "bool", True, "混战时 @ 对方",
       "合并批内多人发言且回复对象不是最后发言者时，回复前 @ 对方；与引用互斥。",
       group="拟人行为"),
    _s("personification_humanize_input_status_enabled", "bool", True, "私聊输入状态",
       "私聊回复且延迟较长时先显示\"对方正在输入\"（仅 NapCat 系协议端支持）。",
       group="拟人行为"),

    _s("personification_webui_require_device_approval", "bool", True, "新设备需审批",
       "WebUI 新设备登录后需由已批准的设备在「设备」页确认才能使用；全新部署的首个设备自动批准，避免锁死。",
       group="运维"),
    _s("personification_webui_expose_admin_list", "bool", False, "登录页公开管理员 QQ",
       "是否在未登录的 WebUI 登录页返回可登录管理员 QQ 列表。公网或反代暴露时建议保持关闭，改为手动输入 QQ。",
       group="运维", advanced=True,
       risk="开启后未登录访客可看到 SUPERUSERS / plugin_admins 中的 QQ。"),
    _s("personification_webui_log_retention_days", "int", 7, "插件日志保留天数",
       "WebUI「插件日志」持久日志保留天数；每日自动清理旧记录。", group="运维", min=1, max=90),
    _s("personification_webui_log_max_entries", "int", 10000, "插件日志最大条数",
       "超过上限时保留最新记录，避免服务器磁盘长期增长。", group="运维", min=100, advanced=True),
    _s("personification_webui_log_capture_level", "str", "INFO", "插件日志最低级别",
       "持久化捕获的最低日志级别；可选 DEBUG/INFO/WARNING/ERROR。", group="运维",
       choices=("DEBUG", "INFO", "WARNING", "ERROR"), advanced=True),
    _s("personification_turn_trace_enabled", "bool", True, "回合追踪",
       "记录拟人回复链路关键阶段，供功能体检和插件日志排查使用。", group="运维"),
    _s("personification_webui_test_group_id", "str", "", "体检测试群",
       "功能体检「实际交互测试」会向该群真实发一条消息，触发完整回复链路。", group="运维"),
    _s("personification_webui_test_user_id", "str", "", "体检测试私聊用户",
       "功能体检「实际交互测试」会向该 QQ 私聊真实发一条消息，触发完整回复链路。", group="运维"),

    # ──────────── 运维 ────────────
    _s("personification_git_auto_update", "bool", False, "Git 自动更新",
       "定期自动拉取插件仓库更新。", group="运维",
       risk="自动更新可能引入不兼容改动，生产环境建议关闭。"),
    _s("personification_git_auto_update_interval", "int", 60, "自动更新间隔（分钟）",
       "git 自动更新的检查周期。", group="运维", min=1, advanced=True),
    _s("personification_git_mirror_prefixes", "list",
       ["https://ghproxy.com", "https://gh-proxy.com", "https://mirror.ghproxy.com", "https://hub.gitmirror.com"],
       "Git 镜像列表",
       "/拟人更新 直连失败时按顺序探测的镜像反代前缀（JSON 数组）；留空关闭镜像回退。",
       group="运维", advanced=True),
    _s("personification_git_mirror_prefix", "str", "", "Git 单镜像（兼容）",
       "单个镜像前缀（向后兼容）；非空时自动并入镜像列表末尾。", group="运维", advanced=True),
)
