DEFAULT_MEMORY_RECALL_TOP_K = 8
MAX_MEMORY_RECALL_TOP_K = 12

DEFAULT_PERSONA_HISTORY_MAX = 60
DEFAULT_PRIVATE_HISTORY_TURNS = 40
MAX_PRIVATE_HISTORY_TURNS = 80

DEFAULT_HISTORY_LEN = 320
DEFAULT_COMPRESS_THRESHOLD = 180
DEFAULT_COMPRESS_KEEP_RECENT = 36

DEFAULT_MESSAGE_EXPIRE_HOURS = 72.0
DEFAULT_GROUP_CONTEXT_EXPIRE_HOURS = 18.0
DEFAULT_GROUP_SUMMARY_EXPIRE_HOURS = 12.0
