DEFAULT_MEMORY_RECALL_TOP_K = 12
MAX_MEMORY_RECALL_TOP_K = 32

DEFAULT_PERSONA_HISTORY_MAX = 60
DEFAULT_PRIVATE_HISTORY_TURNS = 60
MAX_PRIVATE_HISTORY_TURNS = 240

# Long-context memory defaults.  These values are deliberately separate from
# the legacy turn/hour windows: callers can migrate to the bounded, age-aware
# history policy without interpreting an administrator's existing settings.
DEFAULT_PRIVATE_HISTORY_DAYS = 14
DEFAULT_PRIVATE_HISTORY_MAX_MESSAGES = 4000
DEFAULT_GROUP_HISTORY_DAYS = 7
DEFAULT_GROUP_HISTORY_MAX_MESSAGES = 12000
DEFAULT_MEMORY_RETRIEVAL_DAYS = 30
DEFAULT_MEMORY_AUTO_RECALL_TIMEOUT_SECONDS = 5.0
DEFAULT_MEMORY_AUTO_RECALL_CANDIDATE_LIMIT = 32
DEFAULT_MEMORY_AUTO_RECALL_INJECT_LIMIT = 12
DEFAULT_CONTEXT_INPUT_RATIO = 0.50
DEFAULT_CONTEXT_SAFETY_MARGIN_RATIO = 0.05

DEFAULT_HISTORY_LEN = 320
DEFAULT_COMPRESS_THRESHOLD = 180
DEFAULT_COMPRESS_KEEP_RECENT = 36

DEFAULT_MESSAGE_EXPIRE_HOURS = 72.0
DEFAULT_GROUP_CONTEXT_EXPIRE_HOURS = 18.0
DEFAULT_GROUP_SUMMARY_EXPIRE_HOURS = 12.0
