from __future__ import annotations

MAX_STEPS = 10
DEFAULT_AGENT_MAX_STEPS = 10
MIN_AGENT_MAX_STEPS = 3
MAX_AGENT_MAX_STEPS = 16
MAX_EMPTY_LOOKUP_RECOVERY_ROUNDS = 1
MAX_PROMISED_LOOKUP_NO_TOOL_ROUNDS = 2
MAX_LOOKUP_QUERY_VARIANTS = 3
