export type WriteRisk = "none" | "local_write" | "external_read" | "external_write";

export interface FeatureParityContract {
  legacy_view_id: string;
  route: string;
  component: string;
  read_capabilities: string[];
  write_capabilities: string[];
  filters: string[];
  permission: "admin";
  loading_state: string;
  empty_state: string;
  error_state: string;
  write_risk: WriteRisk;
  confirmation_required: boolean;
  unknown_outcome_policy: "not_applicable" | "refresh_before_retry" | "never_auto_retry";
  acceptance_tests: string[];
}

function contract(value: Omit<FeatureParityContract, "permission" | "loading_state" | "empty_state" | "error_state">): FeatureParityContract {
  return {
    ...value,
    permission: "admin",
    loading_state: `${value.legacy_view_id}_loading`,
    empty_state: `${value.legacy_view_id}_empty`,
    error_state: `${value.legacy_view_id}_error`,
  };
}

export const FEATURE_PARITY_CONTRACTS: FeatureParityContract[] = [
  contract({ legacy_view_id: "agent_status", route: "/runtime/agent/status", component: "AgentStatusPage", read_capabilities: ["bot_identity", "turn_states", "runtime_performance", "recent_traces"], write_capabilities: [], filters: ["bot_id"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["agent-runtime-live-data", "agent-rest-fallback"] }),
  contract({ legacy_view_id: "dashboard", route: "/runtime/tokens/24h", component: "TokenStatisticsPage", read_capabilities: ["token_totals", "time_series", "usage_distribution", "provider_quota"], write_capabilities: [], filters: ["window", "bot_id", "sort"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["token-zero-buckets", "token-cost-unconfigured"] }),
  contract({ legacy_view_id: "health", route: "/runtime/health/catalog", component: "FunctionalTestsPage", read_capabilities: ["test_catalog", "test_history", "dependency_state"], write_capabilities: ["run_local_test", "run_external_test"], filters: ["category", "risk", "state"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["health-risk-confirmation", "health-operation-resume"] }),
  contract({ legacy_view_id: "test", route: "/runtime/model-tests/chat", component: "ModelTestsPage", read_capabilities: ["route_catalog", "persona_prompt", "test_history"], write_capabilities: ["chat_test", "media_test", "video_route_probe", "video_turn_test"], filters: ["provider", "model", "media_kind"], write_risk: "external_read", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["model-test-route-vs-turn", "video-evidence-required"] }),
  contract({ legacy_view_id: "proactive", route: "/runtime/proactive/recent", component: "ProactiveDiagnosticsPage", read_capabilities: ["statistics", "recent_records", "next_eligible"], write_capabilities: [], filters: ["scope", "outcome", "target", "cursor"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["proactive-structured-table", "proactive-cursor-pagination"] }),
  contract({ legacy_view_id: "traces", route: "/runtime/traces/index", component: "TracesPage", read_capabilities: ["trace_index", "timeline", "safe_context", "tool_evidence", "final_reply"], write_capabilities: [], filters: ["search", "outcome", "cursor"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["trace-safe-redaction", "trace-detail-lazy-load"] }),
  contract({ legacy_view_id: "qzone", route: "/runtime/qzone/capabilities", component: "QzoneCapabilitiesPage", read_capabilities: ["capability_matrix", "auth_state", "feeds", "operation_history", "reconcile_candidates"], write_capabilities: ["login", "refresh_cookie", "post", "like", "comment", "reply", "forward", "cancel", "reconcile"], filters: ["capability", "operation_state", "feed_id"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["qzone-matrix-render", "qzone-unknown-no-retry"] }),
  contract({ legacy_view_id: "personas", route: "/persona/personas/list", component: "PersonasPage", read_capabilities: ["persona_page", "persona_detail", "favorability", "source_provenance", "avatar_analysis"], write_capabilities: ["refresh_profile", "apply_correction", "refresh_avatar_analysis", "update_policy"], filters: ["search", "group_id", "favorability_level", "sort"], write_risk: "external_read", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["persona-no-profile-text", "persona-server-pagination"] }),
  contract({ legacy_view_id: "groups", route: "/persona/groups/list", component: "GroupsPage", read_capabilities: ["group_page", "group_detail", "members", "aliases", "style", "knowledge", "memes", "agent_state", "schedule", "raw_chat_summary"], write_capabilities: ["rebuild_style", "rebuild_knowledge", "save_alias", "delete_alias", "save_schedule", "generate_schedule", "save_meme", "delete_meme"], filters: ["search", "bot_id", "membership_state", "enabled", "sort"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["groups-confirmed-default", "groups-server-pagination"] }),
  contract({ legacy_view_id: "group_switch", route: "/persona/group-switches/list", component: "GroupSwitchesPage", read_capabilities: ["switch_page", "source_state", "enabled_counts"], write_capabilities: ["enable_group", "disable_group"], filters: ["search", "enabled", "membership_state", "page"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["group-switch-business-table", "group-switch-confirmed-write"] }),
  contract({ legacy_view_id: "memory", route: "/persona/memories/recent", component: "MemoryManagementPage", read_capabilities: ["recent_memories", "memory_detail", "inner_state", "recall_test", "vector_index"], write_capabilities: ["rebuild_vector_index"], filters: ["scope", "source", "status", "search", "cursor"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["memory-structured-detail", "memory-index-rebuild"] }),
  contract({ legacy_view_id: "memory_graph", route: "/persona/memory-palace/graph", component: "MemoryPalacePage", read_capabilities: ["graph", "zones", "relations", "conflicts", "index_state"], write_capabilities: [], filters: ["zone", "relation", "conflict_state"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["memory-palace-graph", "memory-palace-no-flat-json"] }),
  contract({ legacy_view_id: "stickers", route: "/persona/stickers/catalog", component: "StickersPage", read_capabilities: ["sticker_page", "sticker_detail", "index_state", "preview"], write_capabilities: ["upload", "edit", "delete", "incremental_scan", "full_rebuild"], filters: ["search", "mood_tag", "scene_tag", "labeled", "page"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["sticker-pagination", "sticker-crud"] }),
  contract({ legacy_view_id: "persona_prompt", route: "/persona/persona-preview/prompt", component: "PersonaPreviewPage", read_capabilities: ["actual_prompt", "safe_context", "quality_warnings", "sources"], write_capabilities: [], filters: ["bot_id", "scenario"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["persona-preview-no-cot", "persona-preview-sources"] }),
  contract({ legacy_view_id: "persona_builder", route: "/persona/persona-builder/tasks", component: "PersonaBuilderPage", read_capabilities: ["tasks", "candidate", "history", "templates", "qq_profile_candidates"], write_capabilities: ["build", "answer", "apply", "edit_history", "delete_history", "apply_profile_candidate"], filters: ["state", "revision", "search"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["persona-builder-revision", "persona-builder-history-actions"] }),
  contract({ legacy_view_id: "skills", route: "/capability/skills/installed", component: "SkillsPage", read_capabilities: ["installed_skills", "remote_sources", "health", "review_state", "mcp_summary"], write_capabilities: ["toggle_skill", "toggle_remote", "save_source", "review_remote", "reload"], filters: ["search", "enabled", "source", "review_state"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["skill-actions", "skill-health-status"] }),
  contract({ legacy_view_id: "mcp", route: "/capability/mcp/registry", component: "McpManagementPage", read_capabilities: ["registry", "installations", "instance_detail", "tool_catalog", "social_status", "semantic_review"], write_capabilities: ["install", "toggle_instance", "toggle_tool", "uninstall", "reload", "configure_platform", "login", "logout", "semantic_review_actions"], filters: ["search", "installed", "enabled", "platform", "review_state"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["mcp-install-confirmation", "mcp-social-provenance"] }),
  contract({ legacy_view_id: "tool_creator", route: "/capability/tool-creator/tasks", component: "ToolCreatorPage", read_capabilities: ["tasks", "task_detail", "questions", "events", "artifacts", "validation"], write_capabilities: ["create", "answer", "approve", "cancel", "retry"], filters: ["state", "risk", "search"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["tool-creator-lifecycle", "tool-side-effect-label"] }),
  contract({ legacy_view_id: "plugin_knowledge", route: "/capability/plugin-knowledge/catalog", component: "PluginKnowledgePage", read_capabilities: ["catalog", "search", "detail", "coverage", "source_files", "rebuild_state"], write_capabilities: ["rebuild"], filters: ["search", "category", "coverage", "page"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["plugin-knowledge-detail", "plugin-knowledge-rebuild"] }),
  contract({ legacy_view_id: "plugin_manager", route: "/capability/plugins/status", component: "PluginManagementPage", read_capabilities: ["status", "source_benchmark", "available_commits", "operation_history"], write_capabilities: ["benchmark", "check_update", "apply_update"], filters: ["operation_state", "source_state"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["plugin-five-source-ranking", "plugin-shared-update-service"] }),
  contract({ legacy_view_id: "config", route: "/operations/config/general", component: "ConfigCenterPage", read_capabilities: ["category_metadata", "config_page", "provider_models", "cli_discovery", "route_hints"], write_capabilities: ["patch_values", "apply_recommended", "benchmark_search", "apply_speed_sort"], filters: ["search", "category", "modified", "restart_required", "hot_reloadable", "advanced", "secret", "invalid", "page"], write_risk: "external_read", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["config-no-fetch-all", "config-revision-atomic"] }),
  contract({ legacy_view_id: "user_policy", route: "/operations/user-policies/list", component: "UserPoliciesPage", read_capabilities: ["policy_page", "detail", "events", "evidence"], write_capabilities: ["set_override", "clear_auto", "delete_profile_policy"], filters: ["search", "state", "source", "page"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["policy-detail-evidence", "policy-write-confirmation"] }),
  contract({ legacy_view_id: "outbound", route: "/operations/outbound/list", component: "OutboundMessagesPage", read_capabilities: ["message_cursor_page", "detail", "send_evidence", "trace_link"], write_capabilities: ["recall"], filters: ["scope", "outcome", "target", "cursor"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["outbound-structured-table", "outbound-no-resend"] }),
  contract({ legacy_view_id: "data_transfer", route: "/operations/data-transfer/export", component: "DataTransferPage", read_capabilities: ["export_status", "inspect", "dry_run", "journal"], write_capabilities: ["export", "upload", "dry_run", "apply", "rollback"], filters: ["dataset", "state", "journal_id"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["transfer-http-secret-refusal", "transfer-journal-rollback"] }),
  contract({ legacy_view_id: "audit", route: "/operations/audit/records", component: "AuditLogPage", read_capabilities: ["overview", "cursor_page", "detail", "action_catalog"], write_capabilities: [], filters: ["action", "outcome", "admin", "cursor"], write_risk: "none", confirmation_required: false, unknown_outcome_policy: "not_applicable", acceptance_tests: ["audit-cursor-pagination", "audit-redaction"] }),
  contract({ legacy_view_id: "logs", route: "/operations/logs/live", component: "PluginLogsPage", read_capabilities: ["live_stream", "cursor_page", "trace_filter", "detail"], write_capabilities: ["clear"], filters: ["level", "source", "trace_id", "search", "cursor"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "refresh_before_retry", acceptance_tests: ["logs-sse-and-cursor", "logs-clear-confirmation"] }),
  contract({ legacy_view_id: "qq", route: "/operations/qq/accounts", component: "QqManagementPage", read_capabilities: ["accounts", "groups", "friends", "group_members", "announcements", "requests"], write_capabilities: ["change_nickname", "change_signature", "change_avatar", "change_card", "change_title", "delete_announcement", "leave_group", "handle_request", "delete_friend"], filters: ["bot_id", "search", "group_id", "request_state"], write_risk: "external_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["qq-target-confirmation", "qq-unknown-no-retry"] }),
  contract({ legacy_view_id: "devices", route: "/operations/devices/current", component: "DeviceManagementPage", read_capabilities: ["current_device", "authorized", "pending", "trusted"], write_capabilities: ["approve", "revoke", "trust", "untrust", "logout"], filters: ["state", "search"], write_risk: "local_write", confirmation_required: true, unknown_outcome_policy: "never_auto_retry", acceptance_tests: ["device-approval", "device-revoke-confirmation"] }),
];

export const FEATURE_PARITY_BY_VIEW = new Map(FEATURE_PARITY_CONTRACTS.map((item) => [item.legacy_view_id, item]));
